### ISSUE TITLE
The -h flag doesn't seem to work any more

### ISSUE THREAD

**Issue by jbmorley** [inseven/incontext#64]
```
% incontext -h
Traceback (most recent call last):
  File "/usr/local/src/incontext/incontext.py", line 316, in <module>
    main()
  File "/usr/local/src/incontext/incontext.py", line 312, in main
    instance.run(sys.argv[1:])
  File "/usr/local/src/incontext/incontext.py", line 298, in run
    options = self.parser.parse_args(args)
  File "/usr/lib/python3.8/argparse.py", line 1780, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/lib/python3.8/argparse.py", line 1812, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib/python3.8/argparse.py", line 2018, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/usr/lib/python3.8/argparse.py", line 1958, in consume_optional
    take_action(action, args, option_string)
  File "/usr/lib/python3.8/argparse.py", line 1886, in take_action
    action(self, namespace, argument_values, option_string)
  File "/usr/lib/python3.8/argparse.py", line 1056, in __call__
    parser.print_help()
  File "/usr/lib/python3.8/argparse.py", line 2506, in print_help
    self._print_message(self.format_help(), file)
  File "/usr/lib/python3.8/argparse.py", line 2490, in format_help
    return formatter.format_help()
  File "/usr/lib/python3.8/argparse.py", line 294, in format_help
    help = self._root_section.format_help()
  File "/usr/lib/python3.8/argparse.py", line 225, in format_help
    item_help = join([func(*args) for func, args in self.items])
  File "/usr/lib/python3.8/argparse.py", line 225, in <listcomp>
    item_help = join([func(*args) for func, args in self.items])
  File "/usr/lib/python3.8/argparse.py", line 225, in format_help
    item_help = join([func(*args) for func, args in self.items])
  File "/usr/lib/python3.8/argparse.py", line 225, in <listcomp>
    item_help = join([func(*args) for func, args in self.items])
  File "/usr/lib/python3.8/argparse.py", line 553, in _format_action
    parts.append(self._format_action(subaction))
  File "/usr/lib/python3.8/argparse.py", line 541, in _format_action
    help_text = self._expand_help(action)
  File "/usr/lib/python3.8/argparse.py", line 633, in _expand_help
    return self._get_help_string(action) % params
TypeError: unsupported operand type(s) for %: '_Helper' and 'dict'
```

This seems to have broken since switching to the decorator based commands, but I don't really understand what's going on. The documentation for click (https://click.palletsprojects.com/) seems to imply that argparse has some serious issues.

**Comment by jbmorley** [comment]
Fixed as part of 1414cccd6131348b337b673769b2eca40cc52eb6.
